# Generated by Django 6.0.6 on 2026-10-03 21:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectmilestone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='projectgroupmembership',
            constraint=models.UniqueConstraint(fields=('project', 'student'), name='unique_student_per_project'),
        ),
    ]
