# Generated by Django 6.0.6 on 2026-10-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectgroupmembership_unique_student_per_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcontribution',
            name='notes',
            field=models.TextField(blank=True, max_length=10000),
        ),
    ]
