# Generated by Django 6.0.6 on 2026-10-03 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.CharField(blank=True, default='', help_text='Institution-assigned academic level used for course registration.', max_length=10),
        ),
    ]
