# Generated by Django 6.0.6 on 2026-10-04 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='True only while an institution-issued temporary password is active.'),
        ),
    ]
