# Generated by Django 6.0.6 on 2026-10-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lecturer_approval_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default=None, help_text='Set only for accounts that applied as teaching staff. NULL means the account does not participate in lecturer approval at all, which is the state of every pre-existing row. Deliberately separate from is_email_verified: that proves control of an address, this field authorises acting as teaching staff.', max_length=16, null=True),
        ),
    ]
