# Generated by Django 6.0.6 on 2026-10-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_announcement_is_archived_announcement_is_pinned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='body',
            field=models.TextField(max_length=10000),
        ),
    ]
