# Generated by Django 6.0.6 on 2026-10-04 17:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_semester_single_current'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('class_type', models.CharField(choices=[('LECTURE', 'Lecture'), ('LAB', 'Lab'), ('TUTORIAL', 'Tutorial'), ('SEMINAR', 'Seminar'), ('WORKSHOP', 'Workshop'), ('OTHER', 'Other')], default='LECTURE', max_length=20)),
                ('day_of_week', models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='academic.courseoffering')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'academic_class_schedule',
                'ordering': ['day_of_week', 'start_time'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('course_offering', 'day_of_week', 'start_time'), name='unique_active_offering_schedule_start'), models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='schedule_end_after_start')],
            },
        ),
    ]
