# Generated by Django 6.0.6 on 2026-10-05 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_classschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='course_offering',
            field=models.ForeignKey(blank=True, help_text='Offering-specific source of truth; null only for legacy sessions.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='class_sessions', to='academic.courseoffering'),
        ),
    ]
