# Generated by Django 6.0.6 on 2026-10-05 18:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0008_classsession_course_offering'),
        ('accounts', '0006_user_lecturer_approval_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicTerm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('cohort_from', models.PositiveSmallIntegerField()),
                ('cohort_to', models.PositiveSmallIntegerField()),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='enrollment',
            name='source',
            field=models.CharField(choices=[('LEGACY', 'Legacy/manual'), ('CURRICULUM', 'Curriculum')], default='LEGACY', max_length=20),
        ),
        migrations.AddField(
            model_name='semester',
            name='academic_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='semesters', to='academic.academicterm'),
        ),
        migrations.CreateModel(
            name='CurriculumCourse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('classification', models.CharField(choices=[('PROGRAMME_CORE', 'Programme core'), ('SPECIALIZATION_CORE', 'Specialization core'), ('ELECTIVE', 'Elective')], max_length=30)),
                ('is_required', models.BooleanField(default=True)),
                ('academic_term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requirements', to='academic.academicterm')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curriculum_requirements', to='academic.course')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requirements', to='academic.curriculum')),
            ],
        ),
        migrations.AddField(
            model_name='enrollment',
            name='curriculum_requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='generated_enrollments', to='academic.curriculumcourse'),
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programmes', to='academic.department')),
            ],
        ),
        migrations.AddField(
            model_name='curriculum',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curricula', to='academic.programme'),
        ),
        migrations.CreateModel(
            name='ProgrammeLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('specialization_required', models.BooleanField(default=False)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='levels', to='academic.programme')),
            ],
        ),
        migrations.AddField(
            model_name='curriculumcourse',
            name='programme_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requirements', to='academic.programmelevel'),
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specializations', to='academic.programme')),
            ],
        ),
        migrations.AddField(
            model_name='curriculumcourse',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requirements', to='academic.specialization'),
        ),
        migrations.CreateModel(
            name='StudentAcademicProfile',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='academic_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cohort', models.PositiveSmallIntegerField()),
                ('pinned_at', models.DateTimeField(blank=True, null=True)),
                ('curriculum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_profiles', to='academic.curriculum')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_profiles', to='academic.programme')),
                ('programme_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_profiles', to='academic.programmelevel')),
                ('specialization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_profiles', to='academic.specialization')),
            ],
        ),
        migrations.CreateModel(
            name='CurriculumRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('offering_ids', models.JSONField(default=list)),
                ('summary', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic.curriculum')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curriculum_registrations', to='academic.semester')),
                ('programme_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic.programmelevel')),
                ('specialization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='academic.specialization')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='academic.studentacademicprofile')),
            ],
        ),
        migrations.AddConstraint(
            model_name='curriculum',
            constraint=models.UniqueConstraint(fields=('programme', 'version'), name='unique_programme_curriculum_version'),
        ),
        migrations.AddConstraint(
            model_name='curriculum',
            constraint=models.CheckConstraint(condition=models.Q(('cohort_to__gte', models.F('cohort_from'))), name='curriculum_cohort_range_valid'),
        ),
        migrations.AddConstraint(
            model_name='programmelevel',
            constraint=models.UniqueConstraint(fields=('programme', 'code'), name='unique_programme_level'),
        ),
        migrations.AddConstraint(
            model_name='specialization',
            constraint=models.UniqueConstraint(fields=('programme', 'code'), name='unique_programme_specialization'),
        ),
        migrations.AddConstraint(
            model_name='curriculumcourse',
            constraint=models.CheckConstraint(condition=models.Q(('classification', 'ELECTIVE'), ('is_required', True), _negated=True), name='electives_are_optional'),
        ),
        migrations.AddConstraint(
            model_name='curriculumcourse',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('classification', 'PROGRAMME_CORE'), ('specialization__isnull', True)), models.Q(('classification', 'SPECIALIZATION_CORE'), ('specialization__isnull', False)), ('classification', 'ELECTIVE'), _connector='OR'), name='curriculum_classification_scope_valid'),
        ),
        migrations.AddConstraint(
            model_name='curriculumcourse',
            constraint=models.UniqueConstraint(condition=models.Q(('specialization__isnull', True)), fields=('curriculum', 'programme_level', 'academic_term', 'course'), name='unique_common_curriculum_course'),
        ),
        migrations.AddConstraint(
            model_name='curriculumcourse',
            constraint=models.UniqueConstraint(condition=models.Q(('specialization__isnull', False)), fields=('curriculum', 'programme_level', 'academic_term', 'course', 'specialization'), name='unique_specialized_curriculum_course'),
        ),
        migrations.AddConstraint(
            model_name='curriculumregistration',
            constraint=models.UniqueConstraint(fields=('profile', 'semester'), name='unique_student_semester_curriculum'),
        ),
    ]
