# Generated by Django 6.0.6 on 2026-10-08 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0010_carryoverapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='classschedule',
            name='name',
            field=models.CharField(blank=True, default='', help_text='Documented class name (API §22). Required on class creation.', max_length=255),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='day_of_week',
            field=models.CharField(blank=True, choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
