# Generated by Django 6.0.6 on 2026-10-03 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancecorrection',
            name='new_status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('LATE', 'Late'), ('ABSENT', 'Absent'), ('EXCUSED', 'Excused')], default='PRESENT', max_length=20),
        ),
        migrations.AddField(
            model_name='attendancecorrection',
            name='old_status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('LATE', 'Late'), ('ABSENT', 'Absent'), ('EXCUSED', 'Excused')], default='PRESENT', max_length=20),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('LATE', 'Late'), ('ABSENT', 'Absent'), ('EXCUSED', 'Excused')], default='PRESENT', max_length=20),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='verification_method',
            field=models.CharField(choices=[('QR_SCAN', 'QR code scan'), ('MANUAL', 'Manual')], default='QR_SCAN', max_length=20),
        ),
    ]
