# Generated by Django 6.0.6 on 2026-10-06 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendancecorrection_new_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancecheckpoint',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancecheckpoint',
            name='activated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='station_activations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendancecheckpoint',
            name='source',
            field=models.CharField(choices=[('SEED', 'Lecturer seed'), ('CASCADE', 'Activated by a valid scan')], default='SEED', max_length=10),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='mode',
            field=models.CharField(choices=[('PROJECTOR', 'Projected code'), ('STATIONS', 'Student stations')], default='PROJECTOR', max_length=10),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='checkpoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='attendance.attendancecheckpoint'),
        ),
    ]
