# Generated by Django 6.0.6 on 2026-10-04

import apps.files.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academic", "0005_department_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("file", models.FileField(max_length=500, upload_to=apps.files.models.private_upload_path)),
                ("original_name", models.CharField(max_length=255)),
                ("mime_type", models.CharField(max_length=120)),
                ("size_bytes", models.PositiveBigIntegerField()),
                ("sha256", models.CharField(max_length=64)),
                ("status", models.CharField(choices=[("ACTIVE", "Active"), ("ARCHIVED", "Archived")], db_index=True, default="ACTIVE", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("course_offering", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="uploaded_files", to="academic.courseoffering")),
                ("uploaded_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="uploaded_files", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "files_uploaded_file", "ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="LearningMaterial",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True, default="")),
                ("status", models.CharField(choices=[("ACTIVE", "Active"), ("ARCHIVED", "Archived")], db_index=True, default="ACTIVE", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("course_offering", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="materials", to="academic.courseoffering")),
                ("uploaded_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="learning_materials", to=settings.AUTH_USER_MODEL)),
                ("file", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="materials", to="files.uploadedfile")),
            ],
            options={
                "db_table": "files_learning_material",
                "ordering": ["-created_at"],
                "constraints": [models.UniqueConstraint(fields=("file",), name="unique_material_file")],
            },
        ),
    ]
