# Generated by Django 6.0.6 on 2026-09-25 22:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('announcement', 'Announcement'), ('attendance_flag', 'Attendance flag'), ('attendance_correction', 'Attendance correction'), ('role_change', 'Role change'), ('enrollment', 'Enrollment')], max_length=32)),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField()),
                ('related_type', models.CharField(blank=True, default='', help_text='Optional object kind for deep-linking (e.g. announcement).', max_length=40)),
                ('related_id', models.CharField(blank=True, default='', help_text='Optional object id for deep-linking.', max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(help_text='The only account this notification may be read by.', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications_notification',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='ntf_rcpt_read_created_idx')],
            },
        ),
    ]
